### ISSUE TITLE
Release new version for 0.25.0

### ISSUE THREAD

**Issue by wwuck** [MichaelAquilina/flake8-spellcheck#62]
I am trying to use the pandas.txt dictionary but I just realised that it hasn't been released yet to PyPI.  Can we get a new release for this please?

**Comment by MichaelAquilina** [comment]
you are right @wwuck. I must admit that the reason for this is because of a change (#55 ) that altered the way these packages are built and uploaded to PyPi.

I am unfamiliar with the process now and last time that I tried I gave up after getting somewhat frustrated. I'll give this another try again today

**Comment by MichaelAquilina** [comment]
@gaborbernat maybe you can give me a hand? I've tried using the links you provided me in the original PR to figure this out (https://pypa-build.readthedocs.io/en/latest/#python-m-build). It builds just fine, but I just cannot figure out how to increase the package version without breaking everything.

Unfortunately its made releasing this package a lot more complicated than what I remember :(

**Comment by MichaelAquilina** [comment]
Ok scratch that I seem to have figured it out now.

@wwuck you should be able to download the latest version from pypi now

https://pypi.org/project/flake8-spellcheck/0.25.0/
